```{r user-input}
  rm(list = ls(all = T))
  setwd("/Users/macbookpro/data-collector-android/r-scripts/")
  path.person               <- "bogutzky-simon/"
  path.date                 <- "2014-05-22_17-12-49/"
  path.dropbox              <- "/Users/macbookpro/Dropbox/"
  path.activity             <- "running/"

  activity                  <- "Running"
  sex                       <- "m"
  age                       <- "30"
  subsets.total             <- 4
  subsets.internal          <- 3
  length.subsets.internal   <- 5
  output.filename <- "distance-data"
  
```

```{r functions}
  source("./functions.R")
  source("./distance.R")
```

```{r calculate distances}
 
  result <- c()

  for (subset in 1:subsets.total) {
    #subset <- 2
    # read gps data
    file.path <- paste(path.dropbox, "data-flow/final-data/", path.activity, path.person, path.date, "subset-", subset, "/gps-data.csv", sep ="")
    gps.data  <- read.csv(file.path)
  
    times <- gps.data[,1]    
    #convert in seconds
    times <- times/1000
    times <- times - times[1]  
  
    subset.result <- c()
    new.row.names <- c()
    # divide up
    for (internal.subset in 1:subsets.internal) {
      #internal.subset <- 1
      start.time <- (internal.subset-1) * 60 * length.subsets.internal
      end.time <- internal.subset * 60 * length.subsets.internal
      # choose relevant indexes
      gps.data.subset.indexes <- times >= start.time & times <= end.time
      # select those
      #gps.data.subset <- data.frame()
      gps.data.subset <- gps.data[gps.data.subset.indexes,]
      
       distances <- c()
      
        for (i in 2:nrow(gps.data.subset)) {
        #  23,25,26,27,28
          #i <- 25
          lat1 <- gps.data.subset[i-1,2]
          lon1 <- gps.data.subset[i-1,3]
          lat2 <- gps.data.subset[i,2]
          lon2 <- gps.data.subset[i,3]
          d <- distance(lat1, lon1, lat2, lon2)
          if(is.nan(d)) {
            print(paste("Not a Numer in Subset: ", subset, " Internal Subset: ", internal.subset, " Row: ", i))
          }
          distances <- c(distances, d)
        }
      
      # erase nan ######## STRANGE
      distances <- !is.nan(distances)
      
      # sum up
      absolved.meters <- sum(distances)
      
      # calc duration
      start.date <- gps.data.subset[1, 1] / 1000
      end.date <- gps.data.subset[nrow(gps.data.subset), 1] / 1000
      duration <- end.date-start.date
      #as.POSIXct()
      
      # calc avg speed in [m/s]
      average.speed <- absolved.meters / duration     
        
     # internal.subset.results <- c(as.POSIXct(start.date, tz = "Europe/Berlin", origin = "1970-01-01"), as.POSIXct(end.date, tz = "Europe/Berlin", origin = "1970-01-01"), absolved.meters, average.speed, length.subsets.internal)
      
     internal.subset.results <- c(start.date, end.date, absolved.meters, average.speed, duration)
     
     
     
     #row.names(paste("test"))
     subset.result <- rbind(subset.result, internal.subset.results)
     

    new.row.names <- c(new.row.names, paste("Subset ", subset , " - ", internal.subset))

    
     print(paste("Internal Subset ", internal.subset, " done"))
  }
  row.names(subset.result) <- new.row.names
  result <- rbind(result, subset.result)
  print(paste("Subset ", subset, "done"))
}
titles <- c("Start", "End", "Meter", "Speed", "Duration")
result <- rbind(titles, result)
write.csv(result, file = paste(path.dropbox, "data-flow/final-data/", path.activity, path.person, path.date, output.filename, ".csv", sep =""), row.names = T)
```