```{r user-input}
  rm(list = ls(all = T))
  path.person               <- "lastname-firstname/"
  path.date                 <- "YYYY-MM-dd_HH-mm-ss/"
  path.dropbox              <- "dropbox-path/"
  path.activity             <- "activity/"

  activity                  <- "Activity"
  sex                       <- "Sex"
  age                       <- "xx"
  subsets.total             <- 4
  subsets.internal          <- 3
  length.subsets.internal   <- 5
  
  band.range.ulf            <- c(0, .0033)
  band.range.vlf            <- c(.0033, .04)
  band.range.lf             <- c(.04, .15)
  band.range.hf             <- c(.15, .4)
  band.range.vhf            <- c(.4, .5)

  range.amplitudes          <- c(0, 1000 / 10^6)
  range.frequencies         <- c(0, .5)
```

```{r functions}
  source("./functions.R")
```

```{r plot-rr-intervals-and-psd}
  data.srv.flow <- data.frame()
  for (subset in 1:subsets.total) {
  
  # extract fss factors
    file.path   <- paste(path.dropbox, "data-flow/final-data/", path.activity, path.person, path.date, "scale.csv", sep ="")
    fss.items   <- read.csv(file.path)
    fss.factors <- CalculateFlowShortScaleFactors(fss.items)
  
  # extract step intervals 
    file.path <- paste(path.dropbox, "data-flow/final-data/", path.activity, path.person, path.date, "subset-", subset, "/leg-data.csv", sep ="")
    leg.data  <- read.csv(file.path)
      
  # Step intervals in seconds
    times           <- leg.data$Timestamp / 1000
    time.interval   <- 1 / (length(leg.data$Gyroscope.X) / (times[length(times)]))
    indexes         <- DetectMidSwing(times, leg.data$Gyroscope.X, time.interval, c = 1.5, plot = F)
    step.intervals  <- diff(times[indexes])
  
  # Times in seconds
    time.start  <- times[1]
    times       <- times[indexes]
    times       <- times[2:length(indexes)]
      
  # plot rr intervals and psd
  date.end <- fss.factors[subset, ]$timestamp / 1000
  date.start <- (date.end - times[length(times)])
      
  for (internal.subset in 1:subsets.internal) {
        
      # Times in seconds
      time.end        <- time.start + length.subsets.internal * 60 
      indexes.subset  <- times >= time.start & times <= time.end
        
      times.subset            <- times[indexes.subset]
      step.intervals.subset   <- step.intervals[indexes.subset]
      
      file.path     <- paste(path.dropbox, "data-flow/final-data/", path.activity, path.person, substr(path.date, 1, 19), "-", "subset-", subset, "-", internal.subset, "-step-intervals-and-psd.pdf", sep ="")
      
      pdf(file.path, width = 11, height = 8, paper = "a4r")
      
      par(mfrow = c(2, 1), mar = c(5.1, 5.1, 4.1, 2.1))
      plot(times.subset, step.intervals.subset, type = "l", xlab = "Time (s)", ylab = "Step Interval (s)", xaxs = "i", yaxs = "i", xaxt = "n")
      
      title(main = paste("Step Tachogram - Activity: ", activity, ", Sex: ", sex, ", Age: ", age, ", Subset ", subset, "/",  subsets.total, " - ", internal.subset, sep = ""), sub = paste("Start: ", as.POSIXct(date.start, tz = "Europe/Berlin", origin = "1970-01-01"), ", End: ", as.POSIXct(date.end, tz = "Europe/Berlin", origin = "1970-01-01"), sep = ""))
      axis(side = 1, at = seq(0, 900, by = 60))
      axis(side = 3, at = max(times), labels = paste("Flow:", fss.factors$flow[subset]))
      
      step.frequency.domain.parameters <- CalculateHRVFrequencyDomainParameters(times.subset, step.intervals.subset, band.range.ulf, band.range.vlf, band.range.lf, band.range.hf, band.range.vhf, "welch", 4, 256, .5, T, range.frequencies, range.amplitudes)

      dev.off()

      time.start <- time.end

      flow <- NA
      if(internal.subset == subsets.internal) {
        flow <- fss.factors$flow[subset]
      }
      data.srv.flow <- rbind(data.srv.flow, cbind(step.frequency.domain.parameters, flow))
    }
  }
  
  file.path     <- paste(path.dropbox, "data-flow/final-data/", path.activity, path.person, substr(path.date, 1, 19), "-srv-data.csv", sep ="")
  write.csv(data.srv.flow, file.path, row.names = F)

```

```{r srv-parameter-history-against-flow}

  library(extrafont)
  #font_import()
  loadfonts()
  file.path     <- paste(path.dropbox, "data-flow/final-data/", path.activity, path.person, substr(path.date, 1, 19), "-srv-bands-and-flow.pdf", sep ="")
  
  pdf(file.path, width = 14.2191, height = 10.6643, family = "Gill Sans MT")
  par(mfrow = c(3, 1), mar = c(6.1, 6.1, 4.1, 6.1), oma = c(0, 0, 0, 0), mgp = c(3, 1, 0))

  selected.values <- c(2, 3, 5, 6, 8, 9, 11, 12)

  PlotFlow <- function() {
    par(new = T)
    plot(seq(from = 15, to = 60, by = 15), data.srv.flow$flow[!is.na(data.srv.flow$flow)], xlim = c(0, 60), ylim = c(2, 7), axes = F, xlab = NA, ylab = NA, type = "o", pch = 21, bg = terrain.colors(6)[2], cex = 2)
    axis(side = 4, col = terrain.colors(6)[2], cex = 1.5, cex.axis = 1.5)
    mtext(side = 4, line = 3, "Flow", col = terrain.colors(6)[2], cex = 1.5)
    grid()
  }
  
#   plot(seq(from = 5, to = 60, by = 5)[selected.values], data.srv.flow$vlfpowfft[selected.values], type = "o", xlab = "Minute", ylab = expression("Power of VLF band " (ms^2)), xlim = c(0, 60), ylim = c(0, max(data.srv.flow$vlfpowfft[selected.values])), pch = 21, bg = "#3FADCB", cex = 2, cex.lab = 2, cex.axis = 1.5)
#   grid()
#   PlotFlow()
  
  plot(seq(from = 5, to = 60, by = 5)[selected.values], data.srv.flow$lfpowfft[selected.values], type = "o", xlab = "Minute", ylab = expression("Power of LF band " (ms^2)), xlim = c(0, 60), ylim = c(0, max(data.srv.flow$lfpowfft[selected.values])), pch = 21, bg = "#3FADCB", cex = 2, cex.lab = 2, cex.axis = 1.5)
  grid()
  PlotFlow()

title(main = paste("SRV Activity: ", activity, ", Sex: ", sex, ", Age: ", age, ", Date: ", substr(path.date, 1, 10), sep = ""), cex.main = 3)

  plot(seq(from = 5, to = 60, by = 5)[selected.values], data.srv.flow$hfpowfft[selected.values], type = "o", xlab = "Minute", ylab = expression("Power of HF band " (ms^2)), xlim = c(0, 60), ylim = c(0, max(data.srv.flow$hfpowfft[selected.values])), pch = 21, bg = "#3FADCB", cex = 2, cex.lab = 2, cex.axis = 1.5)
  grid()
  PlotFlow()

  plot(seq(from = 5, to = 60, by = 5)[selected.values], data.srv.flow$lfhffft[selected.values], type = "o", xlab = "Minute", ylab = "LF/HF", xlim = c(0, 60), ylim = c(0, max(data.srv.flow$lfhffft[selected.values])), pch = 21, bg = "#3FADCB", cex = 2, cex.lab = 2, cex.axis = 1.5)
  grid()
  PlotFlow()

  dev.off()
```