```{r user-input}
  rm(list = ls(all = T))
  path.person               <- "lastname-firstname/"
  path.date                 <- "YYYY-MM-dd_HH-mm-ss/"
  path.dropbox              <- "dropbox-path/"
  path.activity             <- "activity/"

  activity                  <- "Activity"
  sex                       <- "Sex"
  age                       <- "xx"
  subsets.total             <- 4
  subsets.internal          <- 3
  length.subsets.internal   <- 5
  
  band.range.ulf            <- c(0, .0033)
  band.range.vlf            <- c(.0033, .04)
  band.range.lf             <- c(.04, .15)
  band.range.hf             <- c(.15, .4)
  band.range.vhf            <- c(.4, .5)

  range.amplitudes          <- c(0, 500 / 10^6)
  range.frequencies         <- c(0, .5)
  range.rr.intervals        <- c(.4, .7)
```

```{r functions}
  source("./functions.R")
```

```{r plot-rr-intervals-and-psd}

  data.hrv.flow <- data.frame()
  for (subset in 1:subsets.total) {
  print(subset)
  # extract fss factors
    file.path   <- paste(path.dropbox, "data-flow/final-data/", path.activity, path.person, path.date, "scale.csv", sep ="")
    fss.items <- read.csv(file.path)
    fss.factors <- CalculateFlowShortScaleFactors(fss.items)
  
  # extract rr intervals and psd values 
    file.path       <- paste(path.dropbox, "data-flow/final-data/", path.activity, path.person, path.date, "subset-", subset, "/hrv-data.txt", sep ="")
    
    if(file.exists(file.path)) {
  
      data.kubios.hrv <- read.csv(file.path, header = F, na.strings = "", fill = T, skip = 97, col.names = c("NA1", "Time", "RRInterval", "FFTFrequency", "FFTPSD", "ARFrequency", "ARPSD", "NA2", "NA3", "NA4", "NA5"))
      
      # Times in seconds
      times           <- data.kubios.hrv$Time
      times           <- times[!is.na(times)]
      
      # RR intervals in seconds
      rr.intervals    <- data.kubios.hrv$RRInterval
      rr.intervals    <- rr.intervals[!is.na(rr.intervals)]
      
      # plot rr intervals and psd
      date.end <- fss.factors[subset, ]$timestamp / 1000
      date.start <- (date.end - times[length(times)])
      
      time.start <- times[1]
      
      for (internal.subset in 1:subsets.internal) {
        
        # Times in seconds
        time.end        <- time.start + length.subsets.internal * 60 
        indexes.subset  <- times >= time.start & times <= time.end
        
        times.subset        <- times[indexes.subset]
        rr.intervals.subset <- rr.intervals[indexes.subset]
      
file.path     <- paste(path.dropbox, "data-flow/final-data/", path.activity, path.person, substr(path.date, 1, 19), "-", "subset-", subset, "-", internal.subset, "-rr-intervals-and-psd.pdf", sep ="")
pdf(file.path, width = 11, height = 8, paper = "a4r")
    
        par(mfrow = c(2, 1), mar = c(5.1, 5.1, 4.1, 2.1))
      
        plot(times.subset, rr.intervals.subset, type = "l", xlab = "Time (s)", ylab = "RR Interval (s)", xaxs = "i", yaxs = "i", xaxt = "n", ylim = range.rr.intervals)
        title(main = paste("Tachogram - Activity: ", activity, ", Sex: ", sex, ", Age: ", age, ", Subset ", subset, "/",  subsets.total, " - ", internal.subset, sep = ""), sub = paste("Start: ", as.POSIXct(date.start, tz = "Europe/Berlin", origin = "1970-01-01"), ", End: ", as.POSIXct(date.end, tz = "Europe/Berlin", origin = "1970-01-01"), sep = ""))
        axis(side = 1, at = seq(0, 900, by = 60))
        axis(side = 3, at = max(times), labels = paste("Flow:", fss.factors$flow[subset]))
  
        hrv.frequency.domain.parameters <- CalculateHRVFrequencyDomainParameters(times.subset, rr.intervals.subset, band.range.ulf, band.range.vlf, band.range.lf, band.range.hf, band.range.vhf, "welch", 4, 256, .5, T, range.frequencies, range.amplitudes)      
dev.off()

        time.start <- time.end
        
        flow <- NA
        if(internal.subset == subsets.internal) {
          flow <- fss.factors$flow[subset]
        }

        data.hrv.flow <- rbind(data.hrv.flow, cbind(hrv.frequency.domain.parameters, flow))
      }
    }
  }
  
#   file.path     <- paste(path.dropbox, "data-flow/final-data/", path.activity, path.person, substr(path.date, 1, 19), "-data.csv", sep ="")
#   write.csv(data.hrv.flow, file.path, row.names = F)
```

```{r hrv-parameter-history-against-flow}

  library(extrafont)
  #font_import()
  loadfonts()
  file.path     <- paste(path.dropbox, "data-flow/final-data/", path.activity, path.person, substr(path.date, 1, 19), "-bands-and-flow.pdf", sep ="")
  
  pdf(file.path, width = 14.2191, height = 10.6643)
  par(mfrow = c(3, 1), mar = c(6.1, 6.1, 4.1, 6.1), oma = c(0, 0, 0, 0), mgp = c(3, 1, 0))

  selected.values <- c(2, 3, 5, 6, 8, 9, 11, 12)

  PlotFlow <- function() {
    par(new = T)
    plot(seq(from = 15, to = 60, by = 15), data.hrv.flow$flow[!is.na(data.hrv.flow$flow)], xlim = c(0, 60), ylim = c(2.5, 7), axes = F, xlab = NA, ylab = NA, type = "o", pch = 21, bg = terrain.colors(6)[2], cex = 2)
    axis(side = 4, col = terrain.colors(6)[2], cex = 1.5, cex.axis = 1.5)
    mtext(side = 4, line = 3, "Flow", col = terrain.colors(6)[2], cex = 1.5)
    grid()
  }
  
#   plot(seq(from = 5, to = 60, by = 5)[selected.values], data.hrv.flow$vlfpowfft[selected.values], type = "o", xlab = "Minute", ylab = expression("Power of VLF band " (ms^2)), xlim = c(0, 60), ylim = c(0, max(data.hrv.flow$vlfpowfft[selected.values])), pch = 21, bg = "#3FADCB", cex = 2, cex.lab = 2, cex.axis = 1.5)
#   grid()
#   PlotFlow()
  
  plot(seq(from = 5, to = 60, by = 5)[selected.values], data.hrv.flow$lfpowfft[selected.values], type = "o", xlab = "Minute", ylab = expression("Power of LF band " (ms^2)), xlim = c(0, 60), ylim = c(0, max(data.hrv.flow$lfpowfft[selected.values])), pch = 21, bg = "#3FADCB", cex = 2, cex.lab = 2, cex.axis = 1.5)
  grid()
  PlotFlow()

title(main = paste("Activity: ", activity, ", Sex: ", sex, ", Age: ", age, ", Date: ", substr(path.date, 1, 10), sep = ""), cex.main = 3)

  plot(seq(from = 5, to = 60, by = 5)[selected.values], data.hrv.flow$hfpowfft[selected.values], type = "o", xlab = "Minute", ylab = expression("Power of HF band " (ms^2)), xlim = c(0, 60), ylim = c(0, max(data.hrv.flow$hfpowfft[selected.values])), pch = 21, bg = "#3FADCB", cex = 2, cex.lab = 2, cex.axis = 1.5)
  grid()
  PlotFlow()

  plot(seq(from = 5, to = 60, by = 5)[selected.values], data.hrv.flow$lfhffft[selected.values], type = "o", xlab = "Minute", ylab = "LF/HF", xlim = c(0, 60), ylim = c(0, max(data.hrv.flow$lfhffft[selected.values])), pch = 21, bg = "#3FADCB", cex = 2, cex.lab = 2, cex.axis = 1.5)
  grid()
  PlotFlow()

  dev.off()
```