```{r user-input}
  rm(list = ls(all = T))
  dropbox.path              <- "/Users/simonbogutzky/Privat/Dropbox/"
  activity.path             <- "running/" 
  person.path               <- "buse-patrik/"
  date.path                 <- "2014-02-27/"
  input.filename            <- "2014-02-27-t13-15-52-leg-data" # sensor_BC98 / sensor_BD38
  output.filename           <- "sensor_BC98" # leg-data / ecg-data
  subset.length.in.minutes  <- 15
```

```{r processing-to-new-format}
file.path   <- paste(dropbox.path, "data-flow/raw-data/", activity.path, person.path, date.path, input.filename, ".csv", sep ="")
sensor.data <- read.csv(file.path)
n.col       <- ncol(sensor.data)

for(i in 1:n.col) {
  if (is.factor(sensor.data[,i])) {
    sensor.data[,i] <- as.numeric(levels(sensor.data[,i])[sensor.data[,i]])
  }
}

sensor.data[,1] <- sensor.data[,1] - sensor.data[1,1]

require("stringr")
date.time           <- str_extract(input.filename, "[0-9]{4}-[0-9]{2}-[0-9]{2}-t[0-9]{2}-[0-9]{2}-[0-9]{2}")
sensor.data[,n.col] <- as.numeric(strptime(date.time, "%Y-%m-%d-t%H-%M-%S", tz = "Europe/Berlin")) * 1000 + sensor.data[,1]

if(n.col == 8) {
  colnames(sensor.data) <- c("Timestamp","Accelerometer X","Accelerometer Y","Accelerometer Z","Gyroscope X","Gyroscope Y","Gyroscope Z","System Timestamp")
}

if(n.col == 4) {
  colnames(sensor.data) <- c("Timestamp","ECG RA-LL","ECG LA-LL","System Timestamp")
}

dir.path   <- paste(dropbox.path, "data-flow/processed-data/", activity.path, person.path, gsub("-t", "_", date.time), "/", sep ="")
dir.create(dir.path, recursive = T, showWarnings = F)

write.csv(sensor.data, paste(dir.path, output.filename, ".csv", sep =""), row.names = F)

file.source.path <- paste(dropbox.path, "data-flow/raw-data/", activity.path, person.path, date.path, date.time, "-fss-data.csv", sep ="")
scale.items <- read.csv(file.source.path)
scale.items <- data.frame(scale.items[17:18], scale.items[1:16])
colnames(scale.items) <- c("System Timestamp 01","System Timestamp 02","Item 01","Item 02","Item 03","Item 04","Item 05","Item 06","Item 07","Item 08","Item 09","Item 10","Item 11","Item 12","Item 13","Item 14","Item 15","Item 16")

write.csv(scale.items, paste(dir.path, "scale.csv", sep =""), row.names = F)

```

```{r functions}

NumberOfDuplicates <- function(x) {
  # Return the number of dublicates
  #   x: Vector to check.
  # Returns:
  #   Number of dublicates
  
  n <- length(x)
  x <- x[!duplicated(x)]
  m <- length(x)
  
  return(n - m)
} 

SamplingRate <- function(t) {
  # Return the sampling rate
  #   t: Vector of times in ms.
  # Returns:
  #   The sampling rate
  return(length(t) / ((t[length(t)] - t[1]) / 10^3))
}

DetectMidSwing <- function(t, x, f, c = 1.5, plot = F) {
  # Detects the gait event midswing from gyroscope data from the leg
  #
  # Args:
  #   t: Vector with intervals.
  #   x: Vector to search.
  #   f: Low pass frequency (Hz)
  #   c: Cutoff difference (s)
  # Returns:
  #   Indexes of mid swings
  
  if (plot) {
    par(mfrow = c(2, 1))
    plot(t / 1000, x, type = "l", xlab = "Time (s)", ylab = "Rotation rate X (deg/s)", xaxs = "i", yaxs = "i")
    maxima <- SearchMaxima(x)
    points(t[maxima$Index] / 1000, x[maxima$Index])
  }

  # Filter high frequency noise
  xf <- LPF(x, f, 2)
  xf <- (xf - mean(xf)) / sd(xf)

  if (plot)
    plot(t / 1000, xf, type = "l", xlab = "Time (s)", ylab = "Filtered rotation rate (deg/s)", xaxs = "i", yaxs = "i")
  
  maxima.1 <- SearchMaxima(xf)
  p <- c(0, diff(maxima.1$Maxima)) > c
  maxima.1 <- maxima.1[p & maxima.1$Maxima > 0,]
  
  if (plot)
    points(t[maxima.1$Index] / 1000, xf[maxima.1$Index])
  
  return(maxima.1$Index)
}  

LPF <- function(t, x, f) {
  # Simple low pass filter
  #
  # Args:
  #   t: Time interval between measurements (s)
  #   y: Vector to filter.
  #   
  #   f: Low pass frequency (Hz)
  # Returns:
  #   A data frame with indexes and values of local maxima.
  
  rc <- 1 / (2 * pi * f)
  a  <- t / (t + rc)
  n  <- length(x)
  xf <-x
  for(i in 2:length(x)) {
    xf[i] <- a * x[i] + (1-a) * xf[i-1]
  }
  return(xf)
} 

SearchMaxima <- function(x) {
  # Search of local maxima
  #
  # Args:
  #   x: Vector to search.
  #
  # Returns:
  #   A data frame with indexes and values of local maxima.
  
  # Find locations of local maxima
  # p = 1 at maxima, p otherwise, end point maxima excluded
  n <- length(x) - 2
  p <- sign(sign(x[2:(n + 1)] - x[3:(n + 2)]) - sign(x[1:n] - x[2:(n + 1)]) -.1) + 1
  p <- c(0, p, 0)
  
  # Indices of maxima and corresponding sample
  p <- as.logical(p) 
  i <- 1:length(p)
  return(data.frame(Index = i[p], Maxima = x[p]))
}

CalculateFlowShortScaleFactors <- function(fss.items) {
  timestamp   <- fss.items[,1]
  duration    <- fss.items[,2] - fss.items[,1]
  flow        <- fss.items[,3:12]
  fluency     <- data.frame(fss.items[,10], fss.items[,9], fss.items[,11], fss.items[,6], fss.items[,7], fss.items[,4])
  absorption  <- data.frame(fss.items[,8], fss.items[,3], fss.items[,12], fss.items[,5])
  anxiety     <- fss.items[,13:15]
  fit         <- fss.items[,16:18]
  
  fss.factors <- data.frame(
    timestamp     = timestamp,
    flow          = round(rowMeans(flow), 2), 
    sdflow        = round(apply(flow, 1, sd), 2), 
    fluency       = round(rowMeans(fluency), 2), 
    sdfluency     = round(apply(fluency, 1, sd), 2), 
    absorption    = round(rowMeans(absorption), 2), 
    sdabsorption  = round(apply(absorption, 1, sd), 2), 
    anxiety       = round(rowMeans(anxiety), 2), 
    sdanxiety     = round(apply(anxiety, 1, sd), 2), 
    fit           = round(rowMeans(fit), 2), 
    sdfit         = round(apply(fit, 1, sd), 2),
    duration      = duration
  )
  
  return(fss.factors)
}
```

```{r control}
file.path   <- paste(dropbox.path, "data-flow/raw-data/", activity.path, person.path, date.path, input.filename, ".csv", sep ="")
sensor.data <- read.csv(file.path)
n.col <- ncol(sensor.data)
summary(sensor.data)

print(paste("Number of dublicates:", NumberOfDuplicates(sensor.data[, 1])))
print(paste("Start:", as.POSIXct(sensor.data[1, n.col] / 1000, tz = "Europe/Berlin", origin = "1970-01-01")))
print(paste("Stop:", as.POSIXct(sensor.data[nrow(sensor.data), n.col] / 1000, tz = "Europe/Berlin", origin = "1970-01-01")))
sampling.rate <- round(SamplingRate(sensor.data[, 1]), 0) 
print(paste("Sampling Rate:", sampling.rate, "Hz"))
```

```{r subset}
scale <- read.csv(paste(path.name, directory.name, "/scale.csv", sep =""))
sensor.data[, 1] <- sensor.data[, 1] - sensor.data[1, 1]
l <- subset_length_in_m * 60 * sampling.rate

for(i in 1:nrow(scale)) {
  if(i == 1) {
    m <- 1 
  } else {
    m <- nrow(sensor.data[sensor.data[, nCol] < scale[i - 1, 2],]) - 1
  }
  n <- m + l - 1
  sensor.data.subset <- sensor.data[m:n,]
  sensor.data.subset <- sensor.data.subset[complete.cases(sensor.data.subset),]
  o <- NumberOfDuplicates(sensor.data.subset[, 1])
  print(paste("Number of dublicates:", o))
  print(paste("Start:", as.POSIXct(sensor.data.subset[1, nCol] / 1000, tz = "Europe/Berlin", origin = "1970-01-01"), "/", as.POSIXct(scale[i - 1, 2]/ 1000, tz = "Europe/Berlin", origin = "1970-01-01")))
  print(paste("Stop:", as.POSIXct(sensor.data.subset[nrow(sensor.data.subset), nCol] / 1000, tz = "Europe/Berlin", origin = "1970-01-01"), "/", as.POSIXct(scale[i, 1]/ 1000, tz = "Europe/Berlin", origin = "1970-01-01")))
  print(paste("Sampling Rate:", round(SamplingRate(sensor.data.subset[, 1]), 0), "Hz"))
  
  if(nrow(sensor.data.subset) == l) {
    if(o == 0) {
      write.csv(sensor.data.subset, file = paste(path.name, directory.name, "/", output_filename, "_subset_", i, ".csv", sep =""), row.names = F)
      print(paste("Wrote: ", path.name, directory.name, "/", output_filename, "_subset_", i, ".csv", sep =""))
    }
  } else {
    print(paste("Subset is too short (", l, "):", nrow(sensor.data.subset)))
  } 
}
```

```{r extract-fss-factors}
scale.items <- read.csv(paste(path.name, directory.name, "/scale.csv", sep =""))
fss.factors <- CalculateFlowShortScaleFactors(scale.items)
```

```{r extract-rr-intervals} 
filename.pattern <- "sensor_BD38_subset_[0-9]{1}_hrv.txt"
file.list <- list.files(path = paste(path.name, directory.name, sep =""), pattern = filename.pattern, recursive = T)
i <- 1

# for
kubios.hrv.data <- read.csv(paste(path.name, directory.name, "/", file.list[i], sep =""), header = F, na.strings = "", fill = T, skip = 97, col.names = c("NA1", "Time", "RRInterval", "FFTFrequency", "FFTPSD", "ARFrequency", "ARPSD", "NA2", "NA3", "NA4", "NA5"))
kubios.hrv.data <- kubios.hrv.data[!is.na(kubios.hrv.data$RRInterval),]
rr.intervals <- kubios.hrv.data$RRInterval
# for end
```

```{r extract-hrv-parameters}
filename.pattern <- "sensor_BD38_subset_[0-9]{1}_hrv_spss.txt"
file.list <- list.files(path = paste(path.name, directory.name, sep =""), pattern = filename.pattern, recursive = T)
i <- 1

# for
spss.hrv.data <- read.csv(paste(path.name, directory.name, "/", file.list[i], sep =""))

# for end
```


```{r extract-step-intervals}
filename.pattern <- "sensor_BC98_subset_[0-9]{1}.csv"
file.list <- list.files(path = paste(path.name, directory.name, sep =""), pattern = filename.pattern, recursive = T)
i <- 1

motion.sensor.data  <- read.csv(paste(path.name, directory.name, "/", file.list[i], sep =""))

t   <- motion.sensor.data[, 1] - motion.sensor.data.subset[, 1]
gx  <- -motion.sensor.data[, 5]
fs  <- 1 / (length(gx) / (t[length(t)] / 1000))

ms.indexes <- DetectMidSwing(t, gx, fs, c = 1.5, plot = T)

```

```{r plot}

par(mfrow = c(2, 1))

rr.data <- sensor.bd38.subset.hrv
rr.data$Time <- rr.data$Time - rr.data$Time[1]
plot(rr.data$Time, rr.data$RRInterval, type = "l", xlab = "Time (s)", ylab = "RR Interval (s)", xaxs = "i", yaxs = "i", ylim = c(0.45, 0.6))
# (length(rr.data$RRInterval)) / ((rr.data$Time[nrow(rr.data)] - rr.data$Time[1]) / 60)

title(main = paste("Activity: Walking, Sex: Female, Start: ", as.POSIXct(date.start, tz = "Europe/Berlin", origin = "1970-01-01"), ", End: ", as.POSIXct(date.end, tz = "Europe/Berlin", origin = "1970-01-01"), ", Subset 1/4", sep = ""), sub = paste("LF: ", round(hrv.data$lfpowfft, 1), " ms^2, HF: ", round(hrv.data$hfpowfft, 1), " ms^2, LF/HF: ", round(hrv.data$lfhffft, 1), ", Flow (15min): ", fss.factors$flow[1], sep = ""))

plot(t[indexes] / 1000, c(NA, diff(t[indexes])) / 2000, type = "l", xlab = "Time (s)", ylab = "Step-to-Step Interval (s)", xaxs = "i", yaxs = "i", ylim = c(0.45, 0.6))
title(main = "", sub = paste("Steps per Minute: ", round((length(indexes) * 2) / ((t[indexes[length(indexes)]] - t[indexes[1]]) / 60000), 1),  sep = ""))

```



