```{r user-input}
  rm(list = ls(all = T))
  dropbox.path              <- "dropbox-path/"
  activity.path             <- "activity/" 
  person.path               <- "lastname-firstname/"
  date.path                 <- "YYYY-mm-dd/"  
  input.filename            <- "YYYY-mm-dd_HH-MM-SS-xxx-data"
  output.filename           <- "sensor_XXXX"
```

```{r transformation}
  file.path   <- paste(dropbox.path, "data-flow/raw-data/", activity.path, person.path, date.path, input.filename, ".csv", sep ="")
  sensor.data <- read.csv(file.path)
  n.col       <- ncol(sensor.data)
  
  for(i in 1:n.col) {
    if (is.factor(sensor.data[,i])) {
      sensor.data[,i] <- as.numeric(levels(sensor.data[,i])[sensor.data[,i]])
    }
  }
  
  sensor.data[,1] <- sensor.data[,1] - sensor.data[1,1]
  
  require("stringr")
  date.time           <- str_extract(input.filename, "[0-9]{4}-[0-9]{2}-[0-9]{2}-t[0-9]{2}-[0-9]{2}-[0-9]{2}")
  sensor.data[,n.col] <- as.numeric(strptime(date.time, "%Y-%m-%d-t%H-%M-%S", tz = "Europe/Berlin")) * 1000 + sensor.data[,1]
  
  if(n.col == 8) {
    colnames(sensor.data) <- c("Timestamp","Accelerometer X","Accelerometer Y","Accelerometer Z","Gyroscope X","Gyroscope Y","Gyroscope Z","System Timestamp")
  }
  
  if(n.col == 4) {
    colnames(sensor.data) <- c("Timestamp","ECG RA-LL","ECG LA-LL","System Timestamp")
  }
  
  dir.path   <- paste(dropbox.path, "data-flow/transformed-data/", activity.path, person.path, gsub("-t", "_", date.time), "/", sep ="")
  dir.create(dir.path, recursive = T, showWarnings = F)
  
  write.csv(sensor.data, paste(dir.path, output.filename, ".csv", sep =""), row.names = F)
  
  file.source.path <- paste(dropbox.path, "data-flow/raw-data/", activity.path, person.path, date.path, date.time, "-fss-data.csv", sep ="")
  scale.items <- read.csv(file.source.path)
  scale.items <- data.frame(scale.items[17:18], scale.items[1:16])
  colnames(scale.items) <- c("System Timestamp 01","System Timestamp 02","Item 01","Item 02","Item 03","Item 04","Item 05","Item 06","Item 07","Item 08","Item 09","Item 10","Item 11","Item 12","Item 13","Item 14","Item 15","Item 16")
  
  write.csv(scale.items, paste(dir.path, "scale.csv", sep =""), row.names = F)
```