```{r user-input}
  rm(list = ls(all = T))
  path.person               <- "last-name-first-name/"
  path.date                 <- "YYYY-MM-dd_HH-mm-SS/"
  path.dropbox              <- "~/Dropbox/"
  path.activity             <- "activity/"

  subsets.total             <- 4
```

```{r functions}
  source("./functions.R")
```

```{r plot-rr-intervals-and-step-intervals}

  for (subset in 1:subsets.total) {
    print(paste("Subset:" , subset))
  
    # Extract rr intervals and psd values 
    file.path   <- paste(path.dropbox, "data-flow/final-data/", path.activity, path.person, path.date, "subset-", subset, "/hrv-data.txt", sep ="")
    
    if(file.exists(file.path)) {
      data.kubios.hrv <- read.csv(file.path, header = F, na.strings = "", fill = T, skip = 97, col.names = c("NA1", "rr.time", "RRInterval", "FFTFrequency", "FFTPSD", "ARFrequency", "ARPSD", "NA2", "NA3", "NA4", "NA5"))
      
      # RR times in seconds
      rr.times           <- data.kubios.hrv$rr.time
      rr.times           <- rr.times[!is.na(rr.times)]
      
      # RR intervals in seconds
      rr.intervals    <- data.kubios.hrv$RRInterval
      rr.intervals    <- rr.intervals[!is.na(rr.intervals)]
      rr.time.start   <- rr.times[1]
      
      # Extract step intervals 
      file.path <- paste(path.dropbox, "data-flow/final-data/", path.activity, path.person, path.date, "subset-", subset, "/leg-data.csv", sep ="")
      leg.data  <- read.csv(file.path)
      
      # Step intervals in seconds
      step.times            <- leg.data$Timestamp / 1000
      step.times            <- step.times - step.times[1]
      step.time.interval    <- 1 / (length(leg.data$Gyroscope.X) / (step.times[length(step.times)]))
      indexes               <- DetectMidSwing(step.times, leg.data$Gyroscope.X, step.time.interval, c = 1.5, plot = F)
      if (length(indexes) == 0)
        indexes               <- DetectMidSwing(step.times, -leg.data$Gyroscope.X, step.time.interval, c = 1.5, plot = F)
      step.intervals        <- diff(step.times[indexes])
  
      # Step times in seconds
      step.time.start <- step.times[1]
      step.times      <- step.times[indexes]
      step.times      <- step.times[2:length(indexes)]
      
      # Combine data
      data <- data.frame(rr.intervals, rr.times, c(step.intervals, rep(NA, length(rr.intervals) - length(step.intervals))), c(step.times, rep(NA, length(rr.intervals) - length(step.times))))
      colnames(data) <- c("rrInterval", "rrTime", "strideInterval", "strideTime")

      # Write data
      file.path     <- paste(path.dropbox, "data-flow/final-data/", path.activity, path.person, substr(path.date, 1, 19), "-", "subset-", subset, "-rr-intervals-and-step-intervals.csv", sep ="")
      write.csv(data, file.path, row.names = FALSE)
    }
  }
```